tap "homebrew/bundle"
brew "coreutils"
brew "libedit"
brew "sqlite"
brew "python@3.11"
brew "asdf"
brew "git-secrets"
brew "jq"
brew "gh"
brew "vim"
brew "neovim"
brew "fzf"
brew "nvm"
vscode "Command is only available in WSL or inside a Visual Studio Code terminal."
